### ISSUE TITLE
Help with the GA and GY Networks

### ISSUE THREAD

**Issue by angeruzzi** [Valentyn1997/CausalTransformer#10]
Hi Valentyn,

First of all, I would like to congratulate you and the other authors on the excellent work presented in the paper 
"Causal Transformer for Estimating Counterfactual Outcomes".

I am amazed by the quality and depth of the research, and especially grateful for making the source code available 
in such a structured and didactic manner.

I am studying the code with great interest as I intend to use your work as an inspiration for my own research. 
However, I am having difficulty locating the implementation of the GA and GY networks mentioned in the paper. 
Could you please help me identify where these networks are implemented in the source?

Thank you in advance for your attention and for the significant contribution to the research community.

Best regards,
Alessandro Angeruzzi

**Comment by angeruzzi** [comment]
I think I found it,
they are implemented in the BRTreatmentOutcomeHead class, in the file '\src\models\utils.py'
the methods:
- build_treatment calls the GA
- build_outcome calls the GY
Could you confirm please?

**Comment by Valentyn1997** [comment]
Dear @angeruzzi,

Sorry for the late response.
All correct, you found them in the right place.

Best, 
Valentyn
