### ISSUE TITLE
Provide a runbook

### ISSUE THREAD

**Issue by yudizhangzyd** [Valentyn1997/CausalTransformer#11]
Hi! 
Thanks for the great work, I am wondering if it is possible to provide some more commands for people to play around with.
Somehow this command 
`python3 runnables/train_multi.py -m +dataset=cancer_sim +backbone=ct +backbone/ct_hparams/cancer_sim_domain_conf='0','1','2' exp.seed=10,101,1010,10101,101010`
has some errorsm related to hydra...
    raise ValueError(
ValueError: Config group override must be a string or a list. Got int

Thanks!

**Comment by angeruzzi** [comment]
Hi Yudi, I also had this error and added some quotes in the command,
try this:
python3 runnables/train_multi.py -m +dataset=cancer_sim +backbone=ct "+backbone/ct_hparams/cancer_sim_domain_conf='0','1','2'" "exp.seed=10,101,1010,10101,101010"

**Comment by Valentyn1997** [comment]
Hi @yudizhangzyd!

Thanks! You can also use the backslashes before the quotation marks, for example:

 ```
 python3 runnables/train_multi.py -m +dataset=cancer_sim +backbone=ct +backbone/ct_hparams/cancer_sim_domain_conf=\'0\',\'1\',\'2\' exp.seed=10,101,1010,10101,101010
 ```
 
 I will add it to the main README.md.
 
Also, thank you @angeruzzi for another solution.

Best,
Valentyn
