### ISSUE TITLE
Error in Config group override

### ISSUE THREAD

**Issue by kzintas** [Valentyn1997/CausalTransformer#3]
I am trying to run the example command, but am getting the following error from Hydra:

`ValueError: Config group override must be a string or a list. Got int`

Can you please help to solve this isse?

**Comment by Valentyn1997** [comment]
Hey!
If you are running code from the command line, you could try either `+backbone/ct_hparams/cancer_sim_domain_conf='0','1','2'` or `+backbone/ct_hparams/cancer_sim_domain_conf=\'0\',\'1\',\'2\'`.

**Comment by kzintas** [comment]
Thank you! I tried single quote around parameters according to the Hydra doc, and it worked.

`PYTHONPATH=. CUDA_VISIBLE_DEVICES=0 python3 runnables/train_multi.py -m +dataset=cancer_sim +backbone=ct +'backbone/ct_hparams/cancer_sim_domain_conf="0","1","2"' exp.seed=10,101,1010,10101,101010`
