### ISSUE TITLE
Question about the MSM config parameters

### ISSUE THREAD

**Issue by lishuang1206** [Valentyn1997/CausalTransformer#6]
Hi, thank you so much for your codes, this is a really great work.
May I ask about how to run the MSM? Because when I run the train_msm.py, it requires the dataset.treatment_model, so I use "multilabel". When it calculates the _test_rmses_ for _test_cf_treatment_seq_, the function _get_normalised_n_step_rmses_ requires the _model_type=='decoder'/'g-net'/'mutli'_,  while here the value of _model_type_ is _"msm_regressor"_, if I need change the value? which one should I use? 
Here is the corresponding codes.
`test_rmses = {}
    if hasattr(dataset_collection, 'test_cf_treatment_seq'):  # Test n_step_counterfactual rmse
        test_rmses = msm_regressor.get_normalised_n_step_rmses(dataset_collection.test_cf_treatment_seq)` 
`def get_normalised_n_step_rmses(self, dataset: Dataset, datasets_mc: List[Dataset] = None):
        logger.info(f'RMSE calculation for {dataset.subset_name}.')
        assert self.model_type == 'decoder' or self.model_type == 'multi' or self.model_type == 'g_net'`
Thank you

**Comment by Valentyn1997** [comment]
Hi!
Thanks for raising this issue, this is really a bug.
I pushed a new commit, which adds `... or self.model_type == 'msm_regressor` to the assertion check. 

Best, Valentyn
