### ISSUE TITLE
Example for use with custom data

### ISSUE THREAD

**Issue by JulianKlug** [Valentyn1997/CausalTransformer#8]
Dear developing team, thanks for this great paper/project!

Currently it is quite complicated to guess the required dataset structure based only on the provided code.

Would it be possible to provide a small example or notebook on how to use this model with a custom dataset?

**Comment by Valentyn1997** [comment]
Dear @JulianKlug. Great idea, I added a new markdown explaining the dataset structure here: https://github.com/Valentyn1997/CausalTransformer/blob/main/src/data/dataset-format.md
